# Generated by Django 3.2.3 on 2021-07-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutColaborador', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut de Colaborador')),
                ('imagen', models.ImageField(upload_to='img', verbose_name='Foto de identificacion')),
                ('nombreCompleto', models.CharField(max_length=70, verbose_name='Nombre Completo')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=15, verbose_name='Contrasena')),
            ],
        ),
    ]
